spring:
  druid:
    stat-view-servlet:
      loginUsername: admin
      loginPassword: 123456
  dynamic:
    primary: master #设置默认的数据源或者数据源组,默认值即为master
  datasource:
    master:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/jeepaydb?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: MK+90J8aAWQIjeL7+AFIq0dDQvUgXoih67jwPftfgs918tywCF9pCB3s6oY0apEo8mn+hClDWRmSeZr4mS2IiA==
      druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
        # 配置测试查询语句 orcle:select 1 from dual   sqlserver  mysql SELECT 1
        validationQuery: select 1 from dual
        # 初始化大小，最小，最大
        initialSize: 10
        minIdle: 10
        maxActive: 200
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 180000
        testOnBorrow: false
        testWhileIdle: true
        removeAbandoned: true
        removeAbandonedTimeout: 1800
        logAbandoned: true
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxOpenPreparedStatements: 100
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: config,stat,wall
        #合并多个DruidDatasource的监控数据
        useGlobalDataSourceStat: true
        #通过connectProperties属性来打开mergesql功能罗慢sQL记录
        connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALX6migCbkx3GKoqzk8pZm4DOUKLcNQRQKIpM+8ozY6548A7F7Lx8qieHq26cnIIihw2dbYNtLGAiISOBYg+bqUCAwEAAQ==
    slave:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/jeepaydb?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: MK+90J8aAWQIjeL7+AFIq0dDQvUgXoih67jwPftfgs918tywCF9pCB3s6oY0apEo8mn+hClDWRmSeZr4mS2IiA==
      druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
        # 配置测试查询语句 orcle:select 1 from dual   sqlserver  mysql SELECT 1
        validationQuery: select 1 from dual
        # 初始化大小，最小，最大
        initialSize: 10
        minIdle: 10
        maxActive: 200
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 180000
        testOnBorrow: false
        testWhileIdle: true
        removeAbandoned: true
        removeAbandonedTimeout: 1800
        logAbandoned: true
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxOpenPreparedStatements: 100
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: config,stat,wall
        #合并多个DruidDatasource的监控数据
        useGlobalDataSourceStat: true
        #通过connectProperties属性来打开mergesql功能罗慢sQL记录
        connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALX6migCbkx3GKoqzk8pZm4DOUKLcNQRQKIpM+8ozY6548A7F7Lx8qieHq26cnIIihw2dbYNtLGAiISOBYg+bqUCAwEAAQ==